version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: './build/php'
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - "8000:80"
  db:
    container_name: db
    build: './build/mysql'
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: news
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db